In [3]:
import pandas as pd
import numpy as np
from sklearn import set_config
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

set_config(display='diagram')

In [4]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df.head()

A   B   C   D
0  48  19  36  31
1  75  35  42  34
2  37  79  19  38
3  58  88  86  53
4  12  90  47  97

In [5]:
df1 = pd.DataFrame()
for idx1,col1 in enumerate(df.columns):
    for idx2,col2 in enumerate(df.drop(columns=df.columns[:idx1]).columns):
        df1[col1+'x'+col2] = df.loc[:,col1] * df.loc[:,col2]

df1.head()

AxA   AxB   AxC   AxD   BxB   BxC   BxD   CxC   CxD   DxD
0  2304   912  1728  1488   361   684   589  1296  1116   961
1  5625  2625  3150  2550  1225  1470  1190  1764  1428  1156
2  1369  2923   703  1406  6241  1501  3002   361   722  1444
3  3364  5104  4988  3074  7744  7568  4664  7396  4558  2809
4   144  1080   564  1164  8100  4230  8730  2209  4559  9409

In [8]:
df2 = df.merge(df1, left_index=True, right_index=True)

df2.head()

A   B   C   D   AxA   AxB   AxC   AxD   BxB   BxC   BxD   CxC   CxD   DxD
0  48  19  36  31  2304   912  1728  1488   361   684   589  1296  1116   961
1  75  35  42  34  5625  2625  3150  2550  1225  1470  1190  1764  1428  1156
2  37  79  19  38  1369  2923   703  1406  6241  1501  3002   361   722  1444
3  58  88  86  53  3364  5104  4988  3074  7744  7568  4664  7396  4558  2809
4  12  90  47  97   144  1080   564  1164  8100  4230  8730  2209  4559  9409

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
norm_scal = StandardScaler()

In [13]:
df3 = pd.DataFrame(index=df2.index, columns=df2.columns)

In [14]:
for col in df2.columns:
    df3[col] = norm_scal.fit_transform(df2[col].values.reshape(-1,1))

In [15]:
df3.head()

A         B         C         D       AxA       AxB       AxC  \
0 -0.011301 -0.937798 -0.496650 -0.653961 -0.293826 -0.645818 -0.335355   
1  0.913334 -0.409275 -0.292547 -0.549772  0.809429  0.159468  0.299125   
2 -0.388004  1.044163 -1.074942 -0.410853 -0.604438  0.299559 -0.792699   
3  0.331156  1.341457  1.204207  0.110093  0.058312  1.324854  1.119220   
4 -1.244148  1.407522 -0.122462  1.638202 -1.011390 -0.566841 -0.854719   

        AxD       BxB       BxC       BxD       CxC       CxD       DxD  
0 -0.436079 -0.944951 -0.812724 -0.783813 -0.701620 -0.650584 -0.761757  
1  0.075730 -0.653498 -0.419073 -0.525316 -0.547355 -0.501321 -0.698577  
2 -0.475597  1.038546 -0.403547  0.254045 -1.009819 -0.839076 -0.605265  
3  0.328262  1.545553  2.634976  0.968889  1.309092  0.996088 -0.163007  
4 -0.592224  1.665642  0.963212  2.717720 -0.400672  0.996567  1.975385

In [49]:
df3.shape[1]

14

In [17]:
from sklearn.decomposition import PCA

In [18]:
pca = PCA(n_components=df3.shape[1])

In [19]:
pca.fit_transform(df3)

array([[-2.21577404e+00,  5.18184575e-01, -4.04737116e-01, ...,
        -1.70988083e-01, -1.51333028e-01, -1.64708485e-03],
       [-5.08740981e-01,  1.09262650e+00, -1.13313012e+00, ...,
        -8.88695108e-02, -5.93335732e-02, -1.65675173e-01],
       [-7.27736807e-01, -2.04200140e+00, -1.48600344e+00, ...,
        -1.78544063e-02, -2.32103395e-02, -8.53356769e-02],
       ...,
       [-9.68094993e-01,  2.60197863e+00,  1.07377499e+00, ...,
        -7.86599630e-02, -1.78483467e-01,  1.65925546e-02],
       [ 7.58820050e-01,  1.12336008e+00, -8.81216598e-01, ...,
        -2.74130917e-02, -5.54201863e-02, -1.74709836e-01],
       [ 1.10869559e+00,  2.21544400e-01, -3.52706902e+00, ...,
        -1.88285241e-02,  8.89061452e-02, -9.56219247e-02]])

In [21]:
vec_var = pca.explained_variance_

In [25]:
pca_comp = (vec_var>1).sum()

In [26]:
pca2 = PCA(n_components=pca_comp)

In [28]:
df4 = pca2.fit_transform(df3)

In [32]:
df4.shape

(100, 4)

In [34]:
Z = df['A'] + df['C']*df['C']*df['C']

In [35]:
Z.head()

0     46704
1     74163
2      6896
3    636114
4    103835
dtype: int32

array([[ 0.77813434],
       [-0.901555  ],
       [ 1.25282916],
       [ 0.92419429],
       [-1.66836969],
       [-0.75549505],
       [ 1.43540409],
       [-0.86504001],
       [-0.68246508],
       [-1.26670485],
       [-1.30321984],
       [ 0.55904443],
       [ 1.1432842 ],
       [ 1.07025423],
       [-1.96048958],
       [ 0.8876793 ],
       [ 0.44949947],
       [ 0.01131965],
       [-0.20777027],
       [ 0.04783463],
       [-0.82852502],
       [-1.08412992],
       [ 0.85116432],
       [-0.93806998],
       [-1.66836969],
       [-0.1347403 ],
       [-0.09822531],
       [ 0.66858939],
       [ 1.36237412],
       [ 1.43540409],
       [ 0.85116432],
       [-1.26670485],
       [-1.23018987],
       [-0.57292013],
       [-0.79201004],
       [ 0.8876793 ],
       [ 1.28934414],
       [-0.82852502],
       [ 0.70510437],
       [ 0.6320744 ],
       [-1.26670485],
       [-0.901555  ],
       [-1.01109995],
       [-0.3903452 ],
       [-0.3903452 ],
       [ 1

In [37]:
df2['A'].values.reshape(-1,1)

array([[79],
       [33],
       [92],
       [83],
       [12],
       [37],
       [97],
       [34],
       [39],
       [23],
       [22],
       [73],
       [89],
       [87],
       [ 4],
       [82],
       [70],
       [58],
       [52],
       [59],
       [35],
       [28],
       [81],
       [32],
       [12],
       [54],
       [55],
       [76],
       [95],
       [97],
       [81],
       [23],
       [24],
       [42],
       [36],
       [82],
       [93],
       [35],
       [77],
       [75],
       [23],
       [33],
       [30],
       [47],
       [47],
       [97],
       [63],
       [54],
       [84],
       [92],
       [94],
       [76],
       [72],
       [57],
       [39],
       [45],
       [48],
       [59],
       [76],
       [12],
       [90],
       [15],
       [49],
       [10],
       [63],
       [90],
       [ 0],
       [75],
       [19],
       [38],
       [68],
       [91],
       [24],
       [96],
       [74],
       [72],
       [89],

In [43]:
df3.columns

Index(['A', 'B', 'C', 'D', 'AxA', 'AxB', 'AxC', 'AxD', 'BxB', 'BxC', 'BxD',
       'CxC', 'CxD', 'DxD'],
      dtype='object')

In [44]:
df3['A'] = norm_scal.fit_transform(df2[col].values.reshape(-1,1))

Exception: Data must be 1-dimensional

In [45]:
df3.shape

(0, 14)