In [1]:
import pandas as pd
import numpy as np
from sklearn import set_config
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

set_config(display='diagram')

In [23]:
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df.head()

A   B   C   D
0  79  33  62  83
1  33  44  34  40
2  92  94  17  45
3  83  65  51  50
4  12  68  21   8

In [24]:
df1 = pd.DataFrame()
for idx1,col1 in enumerate(df.columns):
    for idx2,col2 in enumerate(df.drop(columns=df.columns[:idx1]).columns):
        df1[col1+'x'+col2] = df.loc[:,col1] * df.loc[:,col2]

df1.head()

AxA   AxB   AxC   AxD   BxB   BxC   BxD   CxC   CxD   DxD
0  6241  2607  4898  6557  1089  2046  2739  3844  5146  6889
1  1089  1452  1122  1320  1936  1496  1760  1156  1360  1600
2  8464  8648  1564  4140  8836  1598  4230   289   765  2025
3  6889  5395  4233  4150  4225  3315  3250  2601  2550  2500
4   144   816   252    96  4624  1428   544   441   168    64

In [27]:
df2 = df.merge(df1, left_index=True, right_index=True)

In [28]:
df2.head()

A   B   C   D   AxA   AxB   AxC   AxD   BxB   BxC   BxD   CxC   CxD   DxD
0  79  33  62  83  6241  2607  4898  6557  1089  2046  2739  3844  5146  6889
1  33  44  34  40  1089  1452  1122  1320  1936  1496  1760  1156  1360  1600
2  92  94  17  45  8464  8648  1564  4140  8836  1598  4230   289   765  2025
3  83  65  51  50  6889  5395  4233  4150  4225  3315  3250  2601  2550  2500
4  12  68  21   8   144   816   252    96  4624  1428   544   441   168    64

In [8]:
df3 = pd.DataFrame()
for idx1,col1 in enumerate(df.columns):
    for idx2,col2 in enumerate(df.drop(columns=df.columns[:idx1+1]).columns):
        df3[col1+'/'+col2] = df.loc[:,col1] / df.loc[:,col2]

df3.head()

A/B       A/C       A/D       B/C       B/D        C/D
0  1.428571  0.568182  7.142857  0.397727  5.000000  12.571429
1  0.016667  0.071429  0.017544  4.285714  1.052632   0.245614
2  0.590909  0.590909  1.444444  1.000000  2.444444   2.444444
3  3.875000  0.344444  0.794872  0.088889  0.205128   2.307692
4  0.333333  0.187500  0.123288  0.562500  0.369863   0.657534

In [11]:
df4 = df2.merge(df3, left_index=True, right_index=True)
df4.head()

A   B   C   D   AxA   AxB   AxC   AxD   BxB   BxC   BxD   CxC   CxD   DxD  \
0  50  35  88   7  2500  1750  4400   350  1225  3080   245  7744   616    49   
1   1  60  14  57     1    60    14    57  3600   840  3420   196   798  3249   
2  39  66  66  27  1521  2574  2574  1053  4356  4356  1782  4356  1782   729   
3  31   8  90  39   961   248  2790  1209    64   720   312  8100  3510  1521   
4   9  27  48  73    81   243   432   657   729  1296  1971  2304  3504  5329   

        A/B       A/C       A/D       B/C       B/D        C/D  
0  1.428571  0.568182  7.142857  0.397727  5.000000  12.571429  
1  0.016667  0.071429  0.017544  4.285714  1.052632   0.245614  
2  0.590909  0.590909  1.444444  1.000000  2.444444   2.444444  
3  3.875000  0.344444  0.794872  0.088889  0.205128   2.307692  
4  0.333333  0.187500  0.123288  0.562500  0.369863   0.657534

In [23]:
df2.isna().sum()

A      0
B      0
C      0
D      0
AxA    0
AxB    0
AxC    0
AxD    0
BxB    0
BxC    0
BxD    0
CxC    0
CxD    0
DxD    0
dtype: int64

In [25]:
import numpy as np
from sklearn.decomposition import PCA

pca = PCA(n_components=5)
pca.fit(df2.values)

PCA(n_components=5)

In [8]:
from sklearn.decomposition import PCA

In [15]:
from sklearn.preprocessing import StandardScaler

In [11]:
pca = PCA(n_components=df2.shape[1])

In [12]:
pca.fit(df2)

PCA(n_components=14)

In [14]:
df2.columns

Index(['A', 'B', 'C', 'D', 'AxA', 'AxB', 'AxC', 'AxD', 'BxB', 'BxC', 'BxD',
       'CxC', 'CxD', 'DxD'],
      dtype='object')

In [13]:
pca.explained_variance_

array([2.27822855e+07, 1.39067997e+07, 1.20224763e+07, 7.55849564e+06,
       1.02325600e+06, 7.52850983e+05, 6.18779463e+05, 5.98340425e+05,
       3.34847714e+05, 3.01185904e+05, 5.26160261e+01, 3.33029818e+01,
       2.73277733e+01, 1.82788718e+01])

In [22]:
df2.head()

A  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                   B  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                   C  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                   D  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 AxA  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 AxB  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 AxC  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 AxD  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 BxB  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 BxC  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 BxD  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

                                                 CxC  \
0  StandardScaler(copy=array([StandardScaler(copy...   
1  StandardScaler(copy=array([StandardScaler(copy...   
2  StandardScaler(copy=array([StandardScaler(copy...   
3  StandardScaler(copy=array([StandardScaler(copy...   
4  StandardScaler(copy=array([StandardScaler(copy...   

       

In [29]:
norm_scal = StandardScaler()

In [46]:
df3 = pd.DataFrame(index=df2.index, columns=df2.columns)

In [47]:
for col in df2.columns:
    df3[col] = norm_scal.fit_transform(df2[col].values.reshape(-1,1))

In [48]:
df3.head()

A         B         C         D       AxA       AxB       AxC  \
0  0.778134 -0.484610  0.436414  1.094144  0.721963  0.014999  0.813868   
1 -0.901555 -0.106546 -0.549833 -0.563066 -0.997767 -0.526863 -0.731726   
2  1.252829  1.611931 -1.148626 -0.370367  1.463997  2.849098 -0.550806   
3  0.924194  0.615215  0.048960 -0.177668  0.938264  1.322972  0.541670   
4 -1.668370  0.718323 -1.007733 -1.796339 -1.313207 -0.825238 -1.087835   

        AxD       BxB       BxC       BxD       CxC       CxD       DxD  
0  1.773750 -0.669250 -0.145017  0.105055  0.194358  1.229716  1.180755  
1 -0.876531 -0.382374 -0.382346 -0.363249 -0.711342 -0.634139 -0.750599  
2  0.550582  1.954629 -0.338332  0.818274 -1.003471 -0.927058 -0.595404  
3  0.555643  0.392901  0.402566  0.349492 -0.224461 -0.048300 -0.421951  
4 -1.495959  0.528041 -0.411688 -0.944922 -0.952256 -1.220962 -1.311492

In [49]:
df3.shape[1]

14

In [50]:
pca.fit_transform(df3)

array([[ 1.28931684e+00, -1.61226966e+00,  2.33578389e+00, ...,
         8.15283423e-02,  1.31778932e-01, -5.64619672e-02],
       [-1.97933928e+00,  7.66405226e-01, -8.93682948e-01, ...,
        -1.65135885e-01, -3.31599848e-02,  5.93551775e-02],
       [ 1.08149290e+00,  9.37246264e-01, -1.33119089e+00, ...,
        -1.40660379e-01,  1.48525791e-01,  7.75784463e-02],
       ...,
       [-6.45166121e-01, -2.42368673e+00, -4.56734405e-01, ...,
         2.25279055e-03, -4.08202478e-02, -3.36193153e-02],
       [ 1.43638453e+00,  8.45857855e-01,  5.14975387e-01, ...,
        -3.02559894e-02,  1.43813702e-01, -1.19325789e-02],
       [ 1.05617705e+00, -2.42247567e+00,  2.26037776e+00, ...,
         2.90921901e-03,  2.65124747e-01,  1.94339296e-02]])

In [51]:
pca.explained_variance_

array([4.45822999, 3.47692797, 2.98641242, 2.47145971, 0.17144507,
       0.13879708, 0.12175699, 0.08944784, 0.07918197, 0.06967908,
       0.02652507, 0.02330827, 0.01921735, 0.00902534])

In [38]:
norm_scal.fit_transform(df2['A'].values.reshape(-1,1))

array([[ 0.77813434],
       [-0.901555  ],
       [ 1.25282916],
       [ 0.92419429],
       [-1.66836969],
       [-0.75549505],
       [ 1.43540409],
       [-0.86504001],
       [-0.68246508],
       [-1.26670485],
       [-1.30321984],
       [ 0.55904443],
       [ 1.1432842 ],
       [ 1.07025423],
       [-1.96048958],
       [ 0.8876793 ],
       [ 0.44949947],
       [ 0.01131965],
       [-0.20777027],
       [ 0.04783463],
       [-0.82852502],
       [-1.08412992],
       [ 0.85116432],
       [-0.93806998],
       [-1.66836969],
       [-0.1347403 ],
       [-0.09822531],
       [ 0.66858939],
       [ 1.36237412],
       [ 1.43540409],
       [ 0.85116432],
       [-1.26670485],
       [-1.23018987],
       [-0.57292013],
       [-0.79201004],
       [ 0.8876793 ],
       [ 1.28934414],
       [-0.82852502],
       [ 0.70510437],
       [ 0.6320744 ],
       [-1.26670485],
       [-0.901555  ],
       [-1.01109995],
       [-0.3903452 ],
       [-0.3903452 ],
       [ 1

In [37]:
df2['A'].values.reshape(-1,1)

array([[79],
       [33],
       [92],
       [83],
       [12],
       [37],
       [97],
       [34],
       [39],
       [23],
       [22],
       [73],
       [89],
       [87],
       [ 4],
       [82],
       [70],
       [58],
       [52],
       [59],
       [35],
       [28],
       [81],
       [32],
       [12],
       [54],
       [55],
       [76],
       [95],
       [97],
       [81],
       [23],
       [24],
       [42],
       [36],
       [82],
       [93],
       [35],
       [77],
       [75],
       [23],
       [33],
       [30],
       [47],
       [47],
       [97],
       [63],
       [54],
       [84],
       [92],
       [94],
       [76],
       [72],
       [57],
       [39],
       [45],
       [48],
       [59],
       [76],
       [12],
       [90],
       [15],
       [49],
       [10],
       [63],
       [90],
       [ 0],
       [75],
       [19],
       [38],
       [68],
       [91],
       [24],
       [96],
       [74],
       [72],
       [89],

In [43]:
df3.columns

Index(['A', 'B', 'C', 'D', 'AxA', 'AxB', 'AxC', 'AxD', 'BxB', 'BxC', 'BxD',
       'CxC', 'CxD', 'DxD'],
      dtype='object')

In [44]:
df3['A'] = norm_scal.fit_transform(df2[col].values.reshape(-1,1))

Exception: Data must be 1-dimensional

In [45]:
df3.shape

(0, 14)